x-common-variables: &common-variables
  WEB_HOSTNAME: ${WEB_HOSTNAME-localhost}
  WEB_URL: ${WEB_URL-http://localhost:3000}
  API_URL: ${API_URL-http://localhost:4000}

  MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME-root}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD-example}

  ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME-root}
  ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD-example}
  ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME-root}:${MONGO_ROOT_PASSWORD-example}@db:27017/
  # ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ROOT_USERNAME-admin}
  # ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ROOT_PASSWORD-pass}

  SMTP_HOST: ${SMTP_HOST}
  SMTP_USERNAME: ${SMTP_USERNAME}
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  SMTP_FROM: ${SMTP_FROM}

  JWT_SECRET: ${JWT_SECRET}

services:
  web:
    image: nginx:1.27.5
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./web/dist:/usr/share/nginx/html:ro
      - ./web/etc/nginx/conf.d/mjs.conf:/etc/nginx/conf.d/mjs.conf:ro

  api:
    image: node:22.16.0
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      <<: *common-variables

  db:
    image: mongo:8.0.10
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    environment:
      <<: *common-variables

  mongo-express:
    image: mongo-express:1-18
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      <<: *common-variables

volumes:
  db:
